### ISSUE TITLE
High Scores

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#13]
High Scores should really show the top fifty players. It would also be nice, if the player is under the top 50, if they show him as number 51 with his number displayed. E.G

49 Ice_Sabre
50 Andy_Gower
598 Dragon

**Comment by Eagleheart** [comment]
I changed it to top 50. I didn't want to do the showing name if it's below the top 50 thing yet since there aren't even 50 players but then I was like "what the hell" and did it. I lowered the cap to test it and it us working well.
