### ISSUE TITLE
Unit Changes

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#17]
Change:

Tigress, Leonidas to Enchanted Neutral
Druid, Monk to Mundane Good
Lamia, Lamia Queen, Scarecrow Child, Kobold, Draconian, Draconian Captain, to Enchanted Evil
Amarok, Giant Snake to Mundane Neutral

Add in Baku with stats as unit 100
Change Gargoyle to unit 101, not 100

Add in Giant Rat graphic
Use Elephant graphic for Baku

**Comment by Eagleheart** [comment]
All done! Nice rat! I like it. It looks good in the game! I'll feature it as an always added to hand unit for a while~
