### ISSUE TITLE
Attack Animation

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#18]
Check if you have access to the explosion/attack animation graphic from CB. If not, let me know.

Otherwise, reflag this as an Issue and go ahead and add the attack animation. How it works:

When you attack a unit it should play the attack sound effect. The unit you are attacking's graphic should be replaced by the explosion graphic for about a second (I'm not sure how many frames it runs but it plays through at least twice). After it disappears, it should be replaced either be the unit's graphic (if the attack was unsuccessful) or the attacking unit's graphic (if the attack was successful).

**Comment by Eagleheart** [comment]
Funny. I was just trying to get this earlier today but I hadn't seen the issue yet. I don't have it and no one else seems too. Not on the forum either. I can probably find a different animation to use though. There's no attack sound yet either. Not that I have anyway.

**Comment by Eagleheart** [comment]
The newer new one is in, as you've seen. Closing this.
