### ISSUE TITLE
Selectable Units

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#2]
Add blue square over any unit that’s selectable when no units are selected. (19/07/16)

**Comment by Eagleheart** [comment]
I am not sure how to make an image that lets you see through it on this rendering engine yet, so I'll have to figure that out before doing this. Otherwise it will just block the unit so you can't see it.

**Comment by Eagleheart** [comment]
This is almost done. It was actually very easy when I spent ten minutes on it. It's working when your turn starts. I just have to take a minute to make it apply the squares again after you move a unit. Movement and combat highlights are also opaque now.

**Comment by LanceGardner** [comment]
Great, you can close it as soon as we beta test

**Comment by Eagleheart** [comment]
The units are so selectable now that you can't even not select them if you want to. Closing.
