### ISSUE TITLE
Alignment/Morality

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#27]
Should have the appropriate word underneath in the appropriate colour, in front of the number:

Good (Green), in front of the number
Evil (Red) 
Magic (Purple)
Mundane (Orange)

**Comment by Eagleheart** [comment]
The colors are in. There's not really room to put the word next to it there. Maybe above or below? I think it would look cluttered.

**Comment by LanceGardner** [comment]
It's not necessary. I will put it in "More Info" during the summoning phase.

**Comment by Eagleheart** [comment]
Okay. I'll close this then.

**Comment by LanceGardner** [comment]
"Mundane" is meant to be orange, not grey.
"Magic" is meant to be purple, not blue.
"Neutral" and "Enchanted" are meant to be in white.
The words "morality" and "alignment" shouldn't be coloured in the unit stats.

Reopening.
