### ISSUE TITLE
Mute Option

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#28]
Should be an option to mute the game (customary is a loudspeaker icon to click with a cross over it when muted). If you need me to sort the graphics for you, let me know.

**Comment by Eagleheart** [comment]
I considered this earlier but thought it was not needed because both Chrome and Firefox already have the loudspeaker icon on the tabs to mute them...perhaps other browsers do too?

**Comment by LanceGardner** [comment]
Edge doesn't and 3 people I know of have remarked of the need of such a
function, so I think it's best to bow to popular demand. Maybe some don't
know of that option.

**Comment by LanceGardner** [comment]
This can go on the left, under Time. Clickable icon. Also should have one on the lobby screen.
