### ISSUE TITLE
Scrollable Board.

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#3]
Make game board scrollable in both directions. (19/07/16)

**Comment by LanceGardner** [comment]
A word on this, since it's related, in the lobby there should be three map sizes offered:

Small: 15 by 15 (In a 25 player game, Captains start at B2, then spread out to B5 and E2, and so on)
Medium: 23 by 23 (In a 25 player game, Captains start at B2, then spread out to B7 and G2, and so on)
Large: 31 by 31 (In a 25 player game, Captains start at B2, then spread out to B9 and I2, and so on)

**Comment by Eagleheart** [comment]
I'll need captain placement txt files for each map size like we have for the current one.
