### ISSUE TITLE
Undead

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#33]
Undead functions differently to the DD. There is no change in stats. During the daytime undead units disappear, to be replaced by an indestructible "grave" which cannot move, and does not return to the monster until the next night. Undead units are 25% less likely to summon during the day, and if summoned, appear as the grave.

**Comment by Eagleheart** [comment]
Do you want the property to be called 'undead' or 'insubstantial'?

**Comment by LanceGardner** [comment]
Those are two different properties. The grave thing I describe above affects all undead units (including zombies, skeletons, spectres etc). Insubstantial is the inability to lock units in combat and be hit by physical attacks (held by spectral and shadow units only)

**Comment by Eagleheart** [comment]
I guess this is done.
