### ISSUE TITLE
Repeat Summon

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#38]
I picked Snotlet, it worked. On the second round I didn't go to hand screen but when my enemy had selected I autosummoned a second Snotlet. Third round everything went as normal.

**Comment by Eagleheart** [comment]
What turn order?

**Comment by LanceGardner** [comment]
Classic.

**Comment by Eagleheart** [comment]
Did you switch to hand view during the first round and click something?

**Comment by LanceGardner** [comment]
Nope.

**Comment by LanceGardner** [comment]
It's happening again. Come watch.

**Comment by Eagleheart** [comment]
I'm not at home. I was just leaving earlier. I'm not too concerned though. Likely something small.

**Comment by LanceGardner** [comment]
The game's broken atm. Last two games I played it had glitched by the fifth
round to the extent of being unplayable. Prob an easy fix.

**Comment by LanceGardner** [comment]
Still happening.

**Comment by LanceGardner** [comment]
Happens in Standard Turn Order too. I doubt it's related, but I'm flicking back and forth to other tabs in this game - I wasn't when I played you.

**Comment by Eagleheart** [comment]
Fiiiiiiiiixed.
