### ISSUE TITLE
GUI Fixes

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#41]
1.) Faded Cast Type Indicator on gameboard.
2.) Accommodate all widely-used resolutions. 
3.) Scroll bar on chat to match game's scroll bar.
4.) Fix spacing on hand placement. 
5.) Fix chat to .5 larger font or something so we don't get that last line hanging down. Atm it looks too spaced out anyway.

**Comment by Eagleheart** [comment]
4 and 5 are done.

**Comment by LanceGardner** [comment]
2 is the one I'm looking forward to :P

**Comment by Eagleheart** [comment]
1 no longer applies. 2 is done. 3 is...darn, I really wanted to close this...I guess I'll figure out how to do 3...

**Comment by Eagleheart** [comment]
This is done.
