### ISSUE TITLE
Spells

### ISSUE THREAD

**Issue by Eagleheart** [Eagleheart/Paralibrium#46]
Spell format

Spell Name
Spell Percentage (ignore if removing)
Spell Power (-1 if no power)
Spell Range
Target Type (0 - Global / No Target, 1 - Only Can Target Friendly units, 2 - Only can target enemy units, 3 - Can target friendly and enemy units, 4 - Can only target empty squares, 5 - can only target corpses)
Can Target Own Captain? true / false
Can target enemy captain? true/false

Examples

Reveal
1.0
-1
32
3
true
true

Teleportation
.50
-1
7
4
false
false

Possession
.75
5
7
2
false
false

**Comment by LanceGardner** [comment]
They'll need a description as well. I'll stick that on the end.

**Comment by LanceGardner** [comment]
Reveal
-1
1.0
-1
32
3
true
true
-1
Target any enemy unit you suspect of being an illusion. Unlike most other spells, you can cast Reveal an infinite number of times.

Concentrate
-1
1.0
-1
32
0
false
false
-1
Use Concentrate to increase the chance of summoning a unit successfully on your next turn. Unlike most other spells, you can cast Concentrate an infinite number of times.

Alignment I
1.0
0.7
-1
32
0
false
false
-1
Use Alignment I to shift the world morality slightly toward good or evil.

Morality I
1.0
0.7
-1
32
0
false
false
-1
Use Morality I to shift the world morality slightly toward good or evil.

Speed Up
1.0
0.9
10
6
1
true
false
-1
Raise the speed of a unit by 1 point for a duration of six turns.

Resistance Up
1.0
0.9
10
5
1
true
false
-1
Raise the resistance of a unit by 3 points for a duration of six turns.

Defense Up
1.0
0.9
10
5
1
true
false
-1
Raise the defense of a unit by 2 points for a duration of six turns.

Strength Up
1.0
0.9
10
5
1
true
false
-1
Raise the strength of a unit by 1 point for a duration of six turns.

Alignment II
2.0
0.6
-1
32
0
false
false
-1
Use Alignment II to shift the world alignment toward magic or mundane.

Morality II
2.0
0.6
-1
32
0
false
false
-1
Use Morality II to shift the world morality toward good or evil.

Teleport
2.0
0.7
-1
7
4
false
false
-1
Teleport your captain to an empty square. Be careful, if your captain is inside transportation the transport will not teleport - only the captain.

Fireball
2.0
1.0
5
6
2
false
true
targetice,weakfire
Fireball is a medium-strength offensive spell. 

Transformation
2.0
.3
8
4
3
false
false
-1
Use Transformation to (hopefully) render a strong enemy unit less powerful, or one of your own units more powerful. Transformation is like a box of chocolates. You never know what you're going to get.

Possession
3.0
.4
6
7
2
false
false
-1
Take control of an enemy unit and use it to destroy the captain that summoned it!

Alignment III
3.0
0.5
-1
32
0
false
false
-1
Use Alignment I to shift the world alignment dramatically toward magic or mundane.

Morality III
3.0
0.5
-1
32
0
false
false
-1
Use Morality III to shift the world morality dramatically toward good or evil.
