### ISSUE TITLE
Res Bug

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#49]
Gargoyle killed a War Elephant in my last game. 2 str to 7 or 8 defense. So, maybe check the dice are working.

**Comment by Eagleheart** [comment]
I checked the logs (which now save automatically because I'm awesome). The chance to get under was 1000 and the combat roll was 775. So, it was a 1% chance and a 0.775% chance was rolled. Seems to be fine. Just lucky.
