### ISSUE TITLE
Unit Number

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#8]
When you hover over a unit it should show it's level, but not it's unit number. Something like:
## RAT

**ATK:   1   DEF:   1
RAN:  0    RATK:   0
SPD:  2     RES:  1
Description**

**Comment by Eagleheart** [comment]
Can you put in everything just how you want it? Like morality / alignment and all. And percentage should still be there?

**Comment by LanceGardner** [comment]
Yep, will do. % shouldn't be there (but it should be on the hand screen)

**Comment by LanceGardner** [comment]
## RAT (Lance, 95%)

**MUNDANE, NEUTRAL, ANIMAL
ATK:   1   DEF:   1
SPD:  2     MDEF:  1
RAN:  0    RATK:   0
A small, weak unit obsessed with cheese,
rats are only dangerous in large groups.**

**Comment by LanceGardner** [comment]
I actually want to add in a new feature to unit descriptions. It would look like this (the words Special Abilities would also be underlined)

## NIGHT MARE (Lance, 15%)

ENCHANTED, NEUTRAL, GHOST
ATK:   5   DEF:   4
SPD:  2     MDEF:  4
RAN:  0    RATK:   0
Spectral horses that provide excellent protection for your captain.

Special Abilities:
Flying: Unlike other units, flying units can move after unsuccessful attacks, if they have movement points remaining
Ghost: Ghost units cannot be harmed by physical attacks, only by magic or other ghost units
Transport: Any unit with the transportable ability can be placed on top of a transport unit, and will remain inside until the transport unit is destroyed, or until you choose to exit the transport unit

**Comment by LanceGardner** [comment]
Here are the Special Abilities that should show up, in the order they should show up in (I'll place them in this order in the stats file):

Transport: The Captain can ride this unit, and will be invulnerable until the Transport unit is killed.
Flying: Flying units are able to pass over other units without getting trapped in combat. They can also move after unsuccessful attacks, if they have speed points remaining, which makes them excellent hit and run units.
Thieving:  These units have a very small chance of stealing an opponent's card whenever they attack one of their units. If they attack the opponent's Captain, the chance is far higher.
