### ISSUE TITLE
Turn Order

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#81]
Turn Order should follow this format:

Round 1: A B
Round 2: A B
Round 3: A B
Round 4: A B
Round 5: A
Round 6: B A

etc

Obv the round 5 part isn't necessary for games with more than two people. We should discuss team turn order some time.

Remember, room admins should be able to set how often it alternates.

**Comment by Eagleheart** [comment]
I went with:

Round 1: A B
Round 2: A B
Round 3: A B
Round 4: A
Round 5: B A

This keeps it desynced with day/night.

Since this is implemented, I am closing it.
