### ISSUE TITLE
Lobby chat

### ISSUE THREAD

**Issue by LanceGardner** [Eagleheart/Paralibrium#84]
Often on leaving lobby after a game the text chat becomes stuck - this is still an issue.

**Comment by Eagleheart** [comment]
I fixed it when I said I did a while ago. The server still hasn't been updated.

**Comment by LanceGardner** [comment]
Stuff should stay open until the server is updated. There's no way of knowing if it's really fixed, or if we're really talking about the same issue. Things that are fixed on a server only you can access are like a tree falling in the forest with nobody around. ;)

**Comment by Eagleheart** [comment]
Check if this is fixed! I guess I will close it again in the meanwhile.
